# Generated by Django 4.2.7 on 2025-08-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdata',
            options={'permissions': [('view_detailed_analysis', 'Can view the detailed analysis page')]},
        ),
    ]
